name: "Godot CI/CD"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GODOT_VERSION: 3.5.3

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          
      - name: Build
        run: |
          mkdir -p build/web
          godot --export "HTML5" ./build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web